name: Scrape Bazos Reality

on:
  schedule:
    - cron: '0 */2 * * *'  # Každé 2 hodiny
  workflow_dispatch:        # Možnost manuálního spuštění

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas anthropic python-dotenv pytz
    
    - name: Run scraper
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python src/scraper.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/listings.csv
        git commit -m "Update listings" -a || echo "No changes to commit"
        git push